# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parrot.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparrot.proto\x12\x06parrot\" \n\x10\x41udioPathRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t2N\n\x0eWhisperService\x12<\n\nTranscribe\x12\x18.parrot.AudioPathRequest\x1a\x14.parrot.TextResponse2M\n\x15TextSentimentAnalysis\x12\x34\n\x07Predict\x12\x13.parrot.TextRequest\x1a\x14.parrot.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parrot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOPATHREQUEST']._serialized_start=24
  _globals['_AUDIOPATHREQUEST']._serialized_end=56
  _globals['_TEXTRESPONSE']._serialized_start=58
  _globals['_TEXTRESPONSE']._serialized_end=86
  _globals['_TEXTREQUEST']._serialized_start=88
  _globals['_TEXTREQUEST']._serialized_end=115
  _globals['_WHISPERSERVICE']._serialized_start=117
  _globals['_WHISPERSERVICE']._serialized_end=195
  _globals['_TEXTSENTIMENTANALYSIS']._serialized_start=197
  _globals['_TEXTSENTIMENTANALYSIS']._serialized_end=274
# @@protoc_insertion_point(module_scope)
